"""PaperFlow markdown post-processing utilities."""

from __future__ import annotations

import hashlib
import logging
import re
from datetime import datetime

__all__ = [
    "__version__",
    "enhance",
    "postprocess",
    "fix_latex_delimiters",
    "clean_headers_footers",
    "convert_to_footnotes",
    "linkify_figures",
    "linkify_tables",
    "inject_frontmatter",
]

__version__ = "0.1.1"

logger = logging.getLogger(__name__)

REFERENCE_SECTION_PATTERN = re.compile(
    r"^(?:#{1,6}\s*)?(?:\*\*)?(?:References(?:\s+and\s+Notes)?|Bibliography|Works Cited|Reference List|Notes and References)(?:\*\*)?\s*$",
    re.MULTILINE | re.IGNORECASE,
)
HEADINGLESS_REFERENCE_PATTERN = re.compile(
    r"^(?:-\s*)?(?:\[\[#Reference\s+1\]\]|\[1\]\s+\S|1[\.\)]\s+\S)",
    re.MULTILINE,
)
MULTI_CITATION_PATTERN = re.compile(
    r"(?<![!\[\w])\[((\d{1,3})(?:\s*,\s*\d{1,3})+)\](?!\()"
)
RANGE_CITATION_PATTERN = re.compile(
    r"(?<![!\[\w])\[(\d{1,3})\s*[-\u2013\u2014]\s*(\d{1,3})\](?!\()"
)
SINGLE_CITATION_PATTERN = re.compile(
    r"(?<![!\[\w^])\[(\d{1,3})\](?!\()"
)


def enhance(
    raw_markdown: str,
    images: dict | None = None,
    metadata: dict | None = None,
) -> str:
    """
    Enhance raw PDF-extracted Markdown with structured elements.

    Works with output from any parser: Marker, MinerU, Docling,
    LlamaParse, PyMuPDF4LLM, and similar tools.

    Args:
        raw_markdown: Raw markdown from any PDF parser.
        images: Optional dict of {filename: base64_data}.
        metadata: Optional dict with title, authors, source, and similar fields.

    Returns:
        Enhanced markdown string with normalized LaTeX, standard footnotes,
        figure and table links, YAML frontmatter, and cleaned repeated noise.
    """
    _ = images or {}
    metadata = metadata or {}
    md = raw_markdown
    md = fix_latex_delimiters(md)
    md = clean_headers_footers(md)
    md = convert_to_footnotes(md)
    md = linkify_figures(md)
    md = linkify_tables(md)
    md = inject_frontmatter(md, metadata)
    return md


def postprocess(
    raw_markdown: str,
    images: dict | None = None,
    metadata: dict | None = None,
) -> str:
    """Backward-compatible alias for ``enhance``."""
    return enhance(raw_markdown=raw_markdown, images=images, metadata=metadata)


def fix_latex_delimiters(md: str) -> str:
    """Normalize LaTeX delimiters to a Markdown-friendly format."""
    md = re.sub(r"\\\[(.*?)\\\]", r"$$ \1 $$", md, flags=re.DOTALL)
    md = re.sub(r"\\\((.*?)\\\)", r"$ \1 $", md, flags=re.DOTALL)

    for env in ["equation", "align", "align*", "gather", "gather*"]:
        md = re.sub(
            rf"\\begin\{{{env}\}}(.*?)\\end\{{{env}\}}",
            r"$$ \1 $$",
            md,
            flags=re.DOTALL,
        )

    return md


def clean_headers_footers(md: str) -> str:
    """Remove repeated header/footer lines and standalone page numbers."""
    lines = md.split("\n")
    line_counts: dict[str, int] = {}

    for line in lines:
        stripped = line.strip()
        if stripped:
            line_counts[stripped] = line_counts.get(stripped, 0) + 1

    cleaned = []
    for line in lines:
        stripped = line.strip()
        if not stripped or line_counts.get(stripped, 0) <= 3:
            cleaned.append(line)
        elif not re.match(r"^\d+$", stripped):
            cleaned.append(line)

    return "\n".join(cleaned)


def _protect_blocks(text: str) -> tuple[str, list[str]]:
    """Replace code and math blocks with placeholders before regex passes."""
    blocks: list[str] = []

    def save(match: re.Match[str]) -> str:
        blocks.append(match.group(0))
        return f"%%BLOCK_{len(blocks) - 1}%%"

    text = re.sub(r"```.*?```", save, text, flags=re.DOTALL)
    text = re.sub(r"`[^`]+?`", save, text)
    text = re.sub(r"\$\$.*?\$\$", save, text, flags=re.DOTALL)
    text = re.sub(r"\$[^\$\n]+?\$", save, text)
    return text, blocks


def _restore_blocks(text: str, blocks: list[str]) -> str:
    """Restore placeholders generated by ``_protect_blocks``."""
    for index, block in enumerate(blocks):
        text = text.replace(f"%%BLOCK_{index}%%", block)
    return text


def _parse_ref_entries(ref_text: str) -> dict[str, str]:
    """Parse numbered reference entries from a references section."""
    entries: dict[str, str] = {}
    normalized = re.sub(
        r"\[\[#Reference\s+(\d+)\]\]",
        lambda match: f"[{match.group(1)}]",
        ref_text,
    )

    lines = normalized.split("\n")
    current_num: str | None = None
    current_text: list[str] = []

    for line in lines:
        match = re.match(r"^\s*-?\s*\[(\d+)\]\s*(.*)", line)
        if not match:
            match = re.match(r"^\s*(\d{1,3})[\.\)]\s+(.*)", line)
        if match:
            if current_num is not None:
                entries[current_num] = " ".join(current_text).strip()
            current_num = match.group(1)
            current_text = [match.group(2)] if match.group(2) else []
        elif current_num is not None and line.strip():
            current_text.append(line.strip())

    if current_num is not None:
        entries[current_num] = " ".join(current_text).strip()

    return entries


def _looks_like_reference_start(line: str) -> bool:
    stripped = line.strip()
    if not stripped:
        return False
    return bool(
        re.match(r"^(?:-\s*)?\[(?:\d{1,3})\]\s+\S", stripped)
        or re.match(r"^\d{1,3}[\.\)]\s+\S", stripped)
        or re.match(r"^\[\[#Reference\s+\d+\]\]", stripped)
    )


def _find_headingless_reference_start(md: str) -> int | None:
    lines = md.splitlines()
    if not lines:
        return None

    start_index = max(0, int(len(lines) * 0.6))
    for index in range(start_index, len(lines)):
        if not _looks_like_reference_start(lines[index]):
            continue

        hits = 0
        for candidate in lines[index : min(len(lines), index + 18)]:
            if _looks_like_reference_start(candidate):
                hits += 1

        if hits >= 3:
            return sum(len(line) + 1 for line in lines[:index])

    match = HEADINGLESS_REFERENCE_PATTERN.search(md)
    if match:
        return match.start()
    return None


def convert_to_footnotes(md: str) -> str:
    """Convert bracketed citations plus a references list into footnotes."""
    ref_match = REFERENCE_SECTION_PATTERN.search(md)

    if ref_match:
        body = md[: ref_match.start()]
        ref_section = md[ref_match.end() :]
    else:
        bare_start = _find_headingless_reference_start(md)
        if bare_start is None:
            logger.warning("convert_to_footnotes: no references section found")
            return md
        logger.info("convert_to_footnotes: using headingless reference fallback")
        body = md[:bare_start]
        ref_section = md[bare_start:]

    ref_entries = _parse_ref_entries(ref_section)
    if not ref_entries:
        logger.warning("convert_to_footnotes: references section parsed no entries")
        return md

    body, blocks = _protect_blocks(body)

    body = re.sub(
        r"\[\[#Reference\s+(\d+)\]\]",
        lambda match: match.group(0)
        if int(match.group(1)) == 0
        else f"[^{int(match.group(1))}]",
        body,
    )

    def replace_multi(match: re.Match[str]) -> str:
        nums = [num.strip() for num in re.findall(r"\d+", match.group(1))]
        if nums and all(int(num) > 0 for num in nums):
            return "".join(f"[^{num}]" for num in nums)
        return match.group(0)

    body = MULTI_CITATION_PATTERN.sub(replace_multi, body)

    def replace_range(match: re.Match[str]) -> str:
        start, end = int(match.group(1)), int(match.group(2))
        if start == 0 or end == 0 or end < start or end - start > 20:
            return match.group(0)
        return "".join(f"[^{num}]" for num in range(start, end + 1))

    body = RANGE_CITATION_PATTERN.sub(replace_range, body)

    body = SINGLE_CITATION_PATTERN.sub(
        lambda match: match.group(0)
        if int(match.group(1)) == 0
        else f"[^{int(match.group(1))}]",
        body,
    )

    body = _restore_blocks(body, blocks)

    footnotes = "\n## References\n\n"
    for num in sorted(ref_entries.keys(), key=int):
        footnotes += f"[^{num}]: {ref_entries[num]}\n\n"

    return body.rstrip() + "\n\n" + footnotes


def _add_fig_anchors(md: str) -> str:
    """Append ``^fig-N`` anchors to figure captions."""

    def add_anchor(match: re.Match[str]) -> str:
        prefix = match.group(0).rstrip()
        num = match.group(1)
        prefix = re.sub(r"\s*\^fig-\d+$", "", prefix)
        return f"{prefix} ^fig-{num}"

    return re.sub(
        r"^(?:Figure|Fig\.)\s+(\d+)\s*[:.].+",
        add_anchor,
        md,
        flags=re.MULTILINE | re.IGNORECASE,
    )


def linkify_figures(md: str) -> str:
    """Convert figure mentions to Obsidian block-reference links."""
    md = _add_fig_anchors(md)
    patterns = [
        (r"\[Fig\.\s*(\d+)\]", "Fig. {0}"),
        (r"\[Figure\s*(\d+)\]", "Figure {0}"),
        (r"\(Fig\.\s*(\d+)\)", "Fig. {0}"),
        (r"\(Figure\s*(\d+)\)", "Figure {0}"),
    ]

    for pattern, label in patterns:
        md = re.sub(
            pattern,
            lambda match, template=label: (
                f"[[#^fig-{match.group(1)}|{template.format(match.group(1))}]]"
            ),
            md,
            flags=re.IGNORECASE,
        )

    return md


def _add_tab_anchors(md: str) -> str:
    """Append ``^tab-N`` anchors to table captions."""

    def add_anchor(match: re.Match[str]) -> str:
        prefix = match.group(0).rstrip()
        num = match.group(1)
        prefix = re.sub(r"\s*\^tab-\d+$", "", prefix)
        return f"{prefix} ^tab-{num}"

    return re.sub(
        r"^Table\s+(\d+)\s*[:.].+",
        add_anchor,
        md,
        flags=re.MULTILINE | re.IGNORECASE,
    )


def linkify_tables(md: str) -> str:
    """Convert table mentions to Obsidian block-reference links."""
    md = _add_tab_anchors(md)
    patterns = [
        (r"\[Table\s*(\d+)\]", "Table {0}"),
        (r"\(Table\s*(\d+)\)", "Table {0}"),
    ]

    for pattern, label in patterns:
        md = re.sub(
            pattern,
            lambda match, template=label: (
                f"[[#^tab-{match.group(1)}|{template.format(match.group(1))}]]"
            ),
            md,
            flags=re.IGNORECASE,
        )

    return md


def _yaml_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _normalize_author_list(value: object) -> list[str]:
    if value is None:
        return []
    if isinstance(value, str):
        cleaned = value.strip()
        return [cleaned] if cleaned else []
    if isinstance(value, (list, tuple, set)):
        names = []
        for entry in value:
            if isinstance(entry, str):
                cleaned = entry.strip()
                if cleaned:
                    names.append(cleaned)
        return names
    return []


def inject_frontmatter(md: str, metadata: dict) -> str:
    """Prepend YAML frontmatter with paper metadata."""
    title = str(metadata.get("title", "Untitled Paper") or "Untitled Paper").strip()
    authors = _normalize_author_list(metadata.get("authors", []))
    source = str(metadata.get("source", "") or "").strip()

    content_hash = hashlib.md5(md.encode("utf-8")).hexdigest()[:8]
    extracted = datetime.now().strftime("%Y-%m-%d")
    date_value = str(metadata.get("date") or metadata.get("published") or extracted).strip()

    if re.match(r"^\d{4}/\d{2}/\d{2}$", date_value):
        date_value = date_value.replace("/", "-")
    if not re.match(r"^\d{4}-\d{2}-\d{2}$", date_value):
        date_value = extracted

    if authors:
        authors_block = "authors:\n" + "\n".join(
            f"  - {_yaml_quote(author)}" for author in authors
        )
    else:
        authors_block = "authors: []"

    frontmatter = f"""---
title: {_yaml_quote(title)}
{authors_block}
source: {_yaml_quote(source)}
date: "{date_value}"
extracted: "{extracted}"
hash: "{content_hash}"
tags: [paperflow, academic]
---

"""

    return frontmatter + md
